@url = http://localhost:5000
@reservationId = ace15ae8-44f3-4896-9aaf-b520e73269e9
@parkingSpotId = 00000000-0000-0000-0000-000000000002
@userId = 5b784299-561e-4e91-982a-444887a6f6a9

###
GET {{url}}

### 
GET {{url}}/parking-spots
Accept: application/json

### 
POST {{url}}/parking-spots/{{parkingSpotId}}/reservations/vehicle
Content-Type: application/json

{
    "capacity": 1,
    "date": "2023-12-28",
    "employeeName": "John Doe",
    "licensePlate": "XYZ124",
    "userId": "{{userId}}"
}

### 
POST {{url}}/parking-spots/reservations/cleaning
Content-Type: application/json

{
    "date": "2023-12-27"
}

### 
PUT {{url}}/parking-spots/reservations/{{reservationId}}
Content-Type: application/json

{
    "licensePlate": "XYZ124"
}

### 
DELETE {{url}}/parking-spots/reservations/{{reservationId}}

###
POST {{url}}/users
Content-Type: application/json

{
    "email" : "admin@myspot.io",
    "username": "admin",
    "password": "secret",
    "fullname": "John Doe Admin",
    "role": "admin"
}

###
GET {{url}}/users/jwt

###
# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
    "email" : "admin@myspot.io",
    "password": "secret"
}

###
@accessToken = {{sign_in.response.body.accessToken}}

###
GET {{url}}/users/me

###
GET {{url}}/users/{{userId}}
Authorization: Bearer {{accessToken}}

###
GET {{url}}/users
Authorization: Bearer {{accessToken}}