@MySpot.Api_HostAddress = http://localhost:5000
@reservationId = ace15ae8-44f3-4896-9aaf-b520e73269e9
@parkingSpotId = 00000000-0000-0000-0000-000000000002
@userId = 5b784299-561e-4e91-982a-444887a6f6a9

###
GET {{MySpot.Api_HostAddress}}

### 
GET {{MySpot.Api_HostAddress}}/parking-spots
Accept: application/json

### 
POST {{MySpot.Api_HostAddress}}/parking-spots/{{parkingSpotId}}/reservations/vehicle
Content-Type: application/json

{
    "capacity": 1,
    "date": "2023-12-28",
    "employeeName": "John Doe",
    "licensePlate": "XYZ124",
    "userId": "{{userId}}"
}

### 
POST {{MySpot.Api_HostAddress}}/parking-spots/reservations/cleaning
Content-Type: application/json

{
    "date": "2023-12-27"
}

### 
PUT {{MySpot.Api_HostAddress}}/parking-spots/reservations/{{reservationId}}
Content-Type: application/json

{
    "licensePlate": "XYZ124"
}

### 
DELETE {{MySpot.Api_HostAddress}}/parking-spots/reservations/{{reservationId}}

###
POST {{MySpot.Api_HostAddress}}/users
Content-Type: application/json

{
    "email" : "user1@myspot.io",
    "username": "user1",
    "password": "secret",
    "fullname": "John Doe",
    "role": "user"
}

###
GET {{MySpot.Api_HostAddress}}/users

###
GET {{MySpot.Api_HostAddress}}/users/{{userId}}