@MySpot.Api_HostAddress = http://localhost:5000
@reservationId = ace15ae8-44f3-4896-9aaf-b520e73269e9
@parkingSpotId = 00000000-0000-0000-0000-000000000003

###
GET {{MySpot.Api_HostAddress}}

### 
GET {{MySpot.Api_HostAddress}}/reservations
Accept: application/json

### 
GET {{MySpot.Api_HostAddress}}/reservations/{{reservationId}}
Accept: application/json

### 
POST {{MySpot.Api_HostAddress}}/reservations/vehicle
Content-Type: application/json

{
    "parkingSpotId": "{{parkingSpotId}}",
    "date": "2023-12-16",
    "employeeName": "John Doe",
    "licensePlate": "XYZ123"
}

### 
POST {{MySpot.Api_HostAddress}}/reservations/cleaning
Content-Type: application/json

{
    "date": "2023-12-16"
}

### 
PUT {{MySpot.Api_HostAddress}}/reservations/{{reservationId}}
Content-Type: application/json

{
    "licensePlate": "XYZ124"
}

### 
DELETE {{MySpot.Api_HostAddress}}/reservations/{{reservationId}}
